### ISSUE TITLE
Required Content For Website

### ISSUE THREAD

**Issue by RajeshKumarPadhy** [aurpita/aurpita.github.io#1]
All changes to the website made can be evaluated directly by pulling down the latest version of the master branch and running light-server or any other such alternative in the Production folder. 

Before we go further, we need to understand the different sections of the website so that the content can be accordingly developed and images would support the content. I have some doubts like:
1. Are the sections outlined in the Menu(Home, Salon, Awards, Services, Promotions, Gallery and Contact) the final versions for the website or are they just dummy content that came with the template? And more importantly, does any of it apply to your target website structure or shall we have to come up with completely new data for each of the sections?
2. Who are the team members?
3. Are the awards listed real or are they dummy content like wise?
4. What content do you want to show in the Our Stats section?
5. What services and products do you want to show in the Our Services and Our Products section?

**Comment by aurpita** [comment]
Please find below my response to your queries:

1. No content has been modified by us so far. All of it is the dummy data that came with the template. We will have to come up with completely new data for each section.
2. Except Aurpita, there is no one else
3. Dummy content. Comment out this section (don't delete) as well as career opportunities section.
4. Let's comment out the stats section for now. I will enable it when there would be some good stats to show.
5. Products section needs to show the products that Aurpita would use for providing the services, not saleable products. List of the services will be provided by Aurpita.

**Comment by RajeshKumarPadhy** [comment]
Okay Sourin, I made the changes as per the comments above. Please take a look and inform me of any additional changes required. Now we can get working on the content which will further help us decide how to structure the remaining of the website
Please answer the following questions so that I can figure out the requirements:
1. We need content for the following sections: Salon, Services, Products and Promotions, Please rename the sections as per your requirements and based on the dummy content please answer the following
2. What are the 3 types of services you provide
3. What are the 3 products you provide
4. What are the 6 promotions/ specials you offer

I shall create content based on the sections you rename, services you provide, products you want to showcase and the promotions/specials

**Comment by aurpita** [comment]
Please find attached a small description of the content for the salon and the services provided.
You can directly call her on her cellphone and ask her any details that you may require.

Also, about the parallax changes, I think there has been some misunderstanding between us.
I don't want the height of the parallax to be increased, rather the images to be resized appropriately.
Also, the images in parallax are now appearing blurred out. They should be sharp as they were before.
The other thing is, for the 1st & 3rd parallax, when the parallax has filled the screen, I can see the images of the ladies not sticking to the bottom of the parallax. What I am trying to say is that the image should not float in the empty space, rather the end of the image should be touch the parallax bottom. They should not separate at any point of time during scrolling.
In the 5th parallax, without changing the size of the parallax, we need to shrink the size of the image so that lady along with her finger nails can shown properly. If need be, you can tell me the dimensions that needs to be for the image and I shall prepare the image as such in photoshop.

Kindly make these changes and feel free to reach out to Aurpita on her cell 704-220-6390 for any content related questions.
[Nail art Web Site Details.docx](https://github.com/aurpita/aurpita.github.io/files/1073589/Nail.art.Web.Site.Details.docx)

**Comment by aurpita** [comment]
Hi Rajesh

We have send the above required info .Please confirm that you have received
it .
 Your mob . number is out of reach so i cannot reach you .

Thanks
Aurpita
